"""Generate notebooks/03_planning.ipynb"""
import json
import os
NB_VERSION = 4
NB_MINOR = 5
KERNEL_SPEC = {
    "display_name": "Python 3",
    "language": "python",
    "name": "python3",
}
LANG_INFO = {
    "name": "python",
    "version": "3.10.0",
}
CELL_META = {}
def md(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": CELL_META,
        "source": [source],
    }
def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": CELL_META,
        "outputs": [],
        "source": [source],
    }
ALL_CELLS = [
    md(
        '# Notebook 03: The Agent\'s Brain — Planning\n'
        '\n'
        'Tools give an agent hands. Planning gives it a brain — the ability to decompose '
        'complex tasks into steps, decide what to do when, and recover from failures.\n'
        '\n'
        '**Expected time:** ~60 minutes\n'
        '**Prerequisites:** Notebooks 00-02\n'
    ),
    md(
        '## What You\'ll Learn\n'
        '\n'
        '1. Chain-of-Thought: how LLMs decompose problems naturally\n'
        '2. Task decomposition patterns: linear, parallel, conditional\n'
        '3. Plan-then-execute: generate a plan, then follow it with tools\n'
        '4. Multi-tool routing: agent decides *which* tool to use\n'
        '5. Common planning failures and how to catch them\n'
    ),
    md(
        '## Setup\n'
    ),
    code(
        '!pip install openai==1.68.2\n'
        '\n'
        'from agent_helpers import ReactAgent, make_tool, mock_llm\n'
        'import os\n'
        'import getpass\n'
        'import json\n'
        'from pathlib import Path\n'
        '\n'
        '# --- Optional .env file loading (no extra pip installs needed) ---\n'
        'env_path = Path.cwd() / ".env"\n'
        'if env_path.exists():\n'
        '    with open(env_path) as f:\n'
        '        for line in f:\n'
        '            line = line.strip()\n'
        '            if line and not line.startswith("#") and "=" in line:\n'
        '                k, v = line.split("=", 1)\n'
        '                os.environ.setdefault(k.strip(), v.strip())\n'
        '    print("Loaded .env file.")\n'
        'else:\n'
        '    print("No .env file found — you will be prompted for API keys.")\n'
        '    print("  Tip: cp .env.example .env  and fill in your keys to skip prompts.")\n'
        '\n'
        '# --- Pick your provider ---\n'
        'PROVIDER = "openrouter"  # Choose: openrouter, groq, openai\n'
        '# --------------------------\n'
        '\n'
        'MOCK = {\n'
        '    "openrouter": True,\n'
        '    "groq":       True,\n'
        '    "openai":     True,\n'
        '}\n'
        '\n'
        'KEY_ENV_VAR = {\n'
        '    "openrouter": "OPENROUTER_API_KEY",\n'
        '    "groq":       "GROQ_API_KEY",\n'
        '    "openai":     "OPENAI_API_KEY",\n'
        '}\n'
        '\n'
        'CONFIG = {\n'
        '    "openrouter": {\n'
        '        "name": "OpenRouter",\n'
        '        "model": "deepseek/deepseek-v4-flash",\n'
        '        "base_url": "https://openrouter.ai/api/v1",\n'
        '        "key_url": "https://openrouter.ai/keys",\n'
        '    },\n'
        '    "groq": {\n'
        '        "name": "Groq",\n'
        '        "model": "openai/gpt-oss-20b",\n'
        '        "base_url": "https://api.groq.com/openai/v1",\n'
        '        "key_url": "https://console.groq.com/keys",\n'
        '    },\n'
        '    "openai": {\n'
        '        "name": "OpenAI",\n'
        '        "model": "gpt-4o-mini",\n'
        '        "base_url": None,\n'
        '        "key_url": "https://platform.openai.com/api-keys",\n'
        '    },\n'
        '}\n'
        '\n'
        'cfg = CONFIG[PROVIDER]\n'
        'use_mock = MOCK[PROVIDER]\n'
        '\n'
        'if use_mock:\n'
        '    print(f"[{cfg[\'name\']}] Mock mode enabled.")\n'
        '    client = None\n'
        '    model = mock_llm()\n'
        'else:\n'
        '    from openai import OpenAI\n'
        '    api_key = os.environ.get(KEY_ENV_VAR[PROVIDER]) or getpass.getpass(f"Enter your {cfg[\'name\']} API key: ")\n'
        '    kwargs = {"api_key": api_key}\n'
        '    if cfg["base_url"]:\n'
        '        kwargs["base_url"] = cfg["base_url"]\n'
        '    client = OpenAI(**kwargs)\n'
        '\n'
        '    def make_model(client, model=None):\n'
        '        if model is None:\n'
        '            model = cfg["model"]\n'
        '        def fn(messages):\n'
        '            try:\n'
        '                r = client.chat.completions.create(model=model, messages=messages, max_tokens=500)\n'
        '                if not r.choices:\n'
        '                    return "Error: empty response from API"\n'
        '                content = r.choices[0].message.content\n'
        '                return content if content is not None else ""\n'
        '            except Exception as e:\n'
        '                return f"API Error: {type(e).__name__}: {e}"\n'
        '        return fn\n'
        '\n'
        '    model = make_model(client)\n'
        '    print(f"[{cfg[\'name\']}] API key configured. Model: {cfg[\'model\']}")\n'
    ),
    md(
        '## Chain of Thought (CoT)\n'
        '\n'
        'Chain of Thought is the simplest form of planning: tell the LLM to "think step by step" '
        'and it decomposes a complex question into intermediate reasoning steps.\n'
        '\n'
        'No tools yet — just reasoning. This builds the habit of structured thinking before we '
        'add tool execution.'
    ),
    code(
        'query = "A student has 3 lectures, 1 lab, and wants to study 4 hours. '
        'Each lecture is 90 min, lab is 2 hours. How much free time do they have in a 12-hour day?"\n'
        '\n'
        'if not use_mock and client is not None:\n'
        '    with_cot = client.chat.completions.create(\n'
        '        model=cfg["model"],\n'
        '        messages=[\n'
        '            {"role": "system", "content": "Think step by step. Show your reasoning."},\n'
        '            {"role": "user", "content": query},\n'
        '        ],\n'
        '    )\n'
        '    print("WITH Chain of Thought:")\n'
        '    print(with_cot.choices[0].message.content)\n'
        'else:\n'
        '    print("Mock — CoT response:")\n'
        '    print("  Step 1: Convert everything to hours.")\n'
        '    print("  Step 2: 3 lectures × 1.5h = 4.5h")\n'
        '    print("  Step 3: 1 lab = 2h")\n'
        '    print("  Step 4: Study = 4h")\n'
        '    print("  Step 5: Total busy = 4.5 + 2 + 4 = 10.5h")\n'
        '    print("  Step 6: Free = 12 - 10.5 = 1.5h")\n'
    ),
    code(
        'if not use_mock and client is not None:\n'
        '    without_cot = client.chat.completions.create(\n'
        '        model=cfg["model"],\n'
        '        messages=[\n'
        '            {"role": "user", "content": query + "\\nAnswer in one sentence."},\n'
        '        ],\n'
        '    )\n'
        '    print("WITHOUT Chain of Thought:")\n'
        '    print(without_cot.choices[0].message.content)\n'
        '    print("\\nCoT produces more reliable, debuggable answers.")\n'
        'else:\n'
        '    print("Mock — without CoT: They have 1.5 hours free.")\n'
        '    print("Shorter, but you can\'t verify the reasoning.")\n'
    ),
    md(
        '## Task Decomposition Patterns\n'
        '\n'
        'Planning problems come in three shapes. Let\'s see each with a Mermaid diagram '
        'and a concrete example.\n'
    ),
    md(
        '### Pattern 1: Linear Decomposition\n'
        '\n'
        'Steps run in sequence. Each depends on the previous.\n'
        '\n'
        '```mermaid\n'
        'graph LR\n'
        '    A[Research] --> B[Draft] --> C[Review] --> D[Publish]\n'
        '```\n'
        '\n'
        '*Example: "Write a summary of agentic AI."*'
    ),
    code(
        'def linear_planner(task, model_fn):\n'
        '    prompt = (\n'
        '        f"Break this task into exactly 3 sequential steps.\\n"\n'
        '        f"Format each step as: STEP: <short description>\\n"\n'
        '        f"Task: {task}"\n'
        '    )\n'
        '    return model_fn([{"role": "user", "content": prompt}])\n'
        '\n'
        'plan = linear_planner("Write a summary of agentic AI for beginners", model)\n'
        'print("Linear plan:")\n'
        'print(plan)\n'
    ),
    md(
        '### Pattern 2: Parallel Decomposition\n'
        '\n'
        'Independent tasks run in parallel, then merge results.\n'
        '\n'
        '```mermaid\n'
        'graph TD\n'
        '    A[Research angle] --> D[Merge & Write]\n'
        '    B[Research angle 2] --> D\n'
        '    C[Research angle 3] --> D\n'
        '```\n'
        '\n'
        '*Example: "Research pros, cons, and trends of agentic AI, then combine."*'
    ),
    code(
        'def parallel_planner(task, model_fn):\n'
        '    prompt = (\n'
        '        f"Break this task into 3 independent sub-tasks that can run in parallel, "\n'
        '        f"followed by a merge step.\\n"\n'
        '        f"Format: PARALLEL: <step>, PARALLEL: <step>, PARALLEL: <step> → MERGE: <step>\\n"\n'
        '        f"Task: {task}"\n'
        '    )\n'
        '    return model_fn([{"role": "user", "content": prompt}])\n'
        '\n'
        'plan = parallel_planner("Research pros, cons, and future trends of agentic AI", model)\n'
        'print("Parallel plan:")\n'
        'print(plan)\n'
    ),
    md(
        '### Pattern 3: Conditional Decomposition\n'
        '\n'
        'The path depends on a condition. Different inputs take different routes.\n'
        '\n'
        '```mermaid\n'
        'graph TD\n'
        '    Q[Query type?] -->|Math| Calc[Use calculator]\n'
        '    Q -->|Weather| Weather[Check weather API]\n'
        '    Q -->|General| Search[Search web]\n'
        '```\n'
        '\n'
        '*Example: "Route user query to the right tool based on type."*'
    ),
    code(
        'def conditional_planner(task, model_fn):\n'
        '    prompt = (\n'
        '        f"Classify this request into one category: math, weather, search, or other.\\n"\n'
        '        f"Then suggest exactly ONE tool to handle it.\\n"\n'
        '        f"Format: CATEGORY: <type> → TOOL: <tool>\\n"\n'
        '        f"Request: {task}"\n'
        '    )\n'
        '    return model_fn([{"role": "user", "content": prompt}])\n'
        '\n'
        'for task in ["What is 2+2?", "Weather in Copenhagen", "Latest AI news"]:\n'
        '    print(f">>> {task}")\n'
        '    print(conditional_planner(task, model))\n'
        '    print()\n'
    ),
    md(
        '## Plan-then-Execute\n'
        '\n'
        'Now we connect planning to execution. The agent:\n'
        '1. Generates a plan\n'
        '2. Executes each step using tools\n'
        '3. Validates each step result\n'
        '4. Moves to next step or retries\n'
        '\n'
        'This is **Complexity Ladder Level 3**: the agent makes decisions about what to do next.'
    ),
    md(
        '### Tools for Planning\n'
    ),
    code(
        'def search_web(query):\n'
        '    db = {\n'
        '        "agentic ai trends 2026": "Agentic AI is shifting from chat to autonomous task completion. '
        'Major frameworks: LangGraph, CrewAI, AutoGen.",\n'
        '        "python machine learning": "Scikit-learn, PyTorch, and TensorFlow dominate. '
        'New: small language models running locally.",\n'
        '        "pbl project ideas": "Common themes: research assistant agents, '
        'personal scheduling agents, data analysis pipelines.",\n'
        '    }\n'
        '    return db.get(query.lower(), f"No stored results for: {query}")\n'
        '\n'
        'def write_note(note):\n'
        '    return f"Saved note: {note[:50]}..."\n'
        '\n'
        'tools = [\n'
        '    make_tool("search", "Search web for information", search_web),\n'
        '    make_tool("calculator", "Evaluate math expressions", lambda e: str(eval(e))),\n'
        '    make_tool("write_note", "Save a note", write_note),\n'
        ']\n'
        'print("Planning tools ready.")\n'
    ),
    md(
        '### Plan → Execute Loop\n'
        '\n'
        'This function generates a plan and executes each step. '
        'It validates each step\'s output before proceeding.'
    ),
    code(
        'def plan_and_execute(task, model_fn, tools, max_steps=8):\n'
        '    """Generate plan, execute each step, validate, proceed."""\n'
        '    plan_prompt = (\n'
        '        f"Create a step-by-step plan for this task.\\n"\n'
        '        f"Format each step: STEP <N>: <action> | tool: <tool_name> | input: <args>\\n"\n'
        '        f"Available tools: calculator, search, write_note\\n"\n'
        '        f"Task: {task}"\n'
        '    )\n'
        '    plan_text = model_fn([{"role": "user", "content": plan_prompt}])\n'
        '    print("GENERATED PLAN:")\n'
        '    print(plan_text)\n'
        '    print("\\n--- EXECUTING ---\\n")\n'
        '\n'
        '    agent = ReactAgent(model=model_fn, tools=tools, max_steps=max_steps)\n'
        '    result = agent.run(task)\n'
        '    print("FINAL RESULT:")\n'
        '    print(result)\n'
        '    return result\n'
    ),
    code(
        'task = "Research latest agentic AI trends and write a short summary note"\n'
        '\n'
        'if not use_mock and client is not None:\n'
        '    plan_and_execute(task, model, tools)\n'
        'else:\n'
        '    print("Mock plan-execute flow:")\n'
        '    print("  STEP 1: Search for agentic AI trends | tool: search | input: agentic AI trends 2026")\n'
        '    print("  STEP 2: Process search results")\n'
        '    print("  STEP 3: Write summary note | tool: write_note | input: ...")\n'
        '    print("\\nPlan validation: each step verified before next.")\n'
    ),
    md(
        '### Step Validation\n'
        '\n'
        'A key improvement: check each step\'s output before moving on. '
        'If a step fails, the agent retries or adjusts.'
    ),
    code(
        'def validated_plan(task, model_fn, tools, max_retries=2):\n'
        '    """Plan with per-step validation and retry."""\n'
        '    prompt = f"Create 3-4 numbered steps for: {task}"\n'
        '    plan = model_fn([{"role": "user", "content": prompt}])\n'
        '    print("Plan:", plan, "\\n")\n'
        '\n'
        '    if not plan or not isinstance(plan, str) or plan.startswith("API Error:"):\n'
        '        print(f"  \u2717 Plan generation failed: {plan}")\n'
        '        return ""\n'
        '\n'
        '    import re\n'
        '    steps = []\n'
        '    current = []\n'
        '    for line in plan.split("\\n"):\n'
        '        s = line.strip()\n'
        '        if re.match(r\'^\\d+[.\\)] \', s):\n'
        '            if current:\n'
        '                steps.append(" ".join(current))\n'
        '            current = [s]\n'
        '        elif current and s:\n'
        '            current.append(s)\n'
        '    if current:\n'
        '        steps.append(" ".join(current))\n'
        '    if not steps:\n'
        '        steps = [s for s in plan.split("\\n") if s.strip()][:4]\n'
        '    print(f"Executing {len(steps)} steps...\\n")\n'
        '\n'
        '    results = []\n'
        '    history = []\n'
        '\n'
        '    for i, step in enumerate(steps):\n'
        '        for attempt in range(max_retries + 1):\n'
        '            ctx = f"Your overall task: {task}"\n'
        '            if history:\n'
        '                ctx += "\\nCompleted so far:\\n" + "\\n".join(history)\n'
        '            result = model_fn([\n'
        '                {"role": "system", "content": ctx},\n'
        '                {"role": "user", "content": f"Execute step {i+1}: {step}"}\n'
        '            ])\n'
        '            validation = model_fn([\n'
        '                {"role": "system", "content": "Reply ONLY with YES or NO."},\n'
        '                {"role": "user", "content":\n'
        '                 f"Did the result complete the step?\\nStep: {step}\\nResult: {result}"}\n'
        '            ])\n'
        '            if "YES" in validation.upper():\n'
        '                results.append(result)\n'
        '                history.append(f"Step {i+1}: completed")\n'
        '                print(f"  \u2713 Step {i+1} passed")\n'
        '                break\n'
        '            else:\n'
        '                print(f"  \u2717 Step {i+1} failed (attempt {attempt+1}), retrying...")\n'
        '        else:\n'
        '            print(f"  \u2717 Step {i+1} failed after {max_retries} retries, skipping")\n'
        '\n'
        '    return "\\n".join(results)\n'
        '\n'
        'if not use_mock and client is not None:\n'
        '    validated_plan("Explain the benefits and risks of agentic AI in healthcare", model, tools)\n'
        'else:\n'
        '    print("Mock \u2014 validation flow:")\n'
        '    print("  \u2713 Step 1 passed")\n'
        '    print("  \u2713 Step 2 passed")\n'
        '    print("  \u2717 Step 3 failed (attempt 1), retrying...")\n'
        '    print("  \u2713 Step 3 passed (attempt 2)")\n'
        '    print("\\nValidation prevents garbage-in-garbage-out through the plan.")\n'
    ),

    md(
        '## Multi-Tool Routing\n'
        '\n'
        'A more advanced pattern: the agent looks at the query, decides what *kind* of task it is, '
        'and routes to the appropriate tool automatically.'
    ),
    code(
        'def router_agent(query, model_fn):\n'
        '    """Classify query and call the right tool."""\n'
        '    classification = model_fn([{"role": "user", "content": (\n'
        '        f"Classify this query as one of: math, weather, file, search, other.\\n"\n'
        '        f"Reply with just the category.\\n"\n'
        '        f"Query: {query}"\n'
        '    )}])\n'
        '\n'
        '    category = classification.strip().lower()\n'
        '\n'
        '    if category == "math":\n'
        '        return "ROUTING → calculator"\n'
        '    elif category == "weather":\n'
        '        return "ROUTING → weather tool"\n'
        '    elif category == "search":\n'
        '        return "ROUTING → web search"\n'
        '    else:\n'
        '        return f"ROUTING → general LLM response"\n'
        '\n'
        'for q in ["What is 144 / 12?", "Weather in Tokyo", "Tell me about PBL"]:\n'
        '    print(f">>> {q}")\n'
        '    print(f"    {router_agent(q, model)}")\n'
    ),
    md(
        '## What Breaks?\n'
    ),
    md(
        '### Break 1: Circular Plan Dependencies\n'
        '\n'
        'Step A needs Step B\'s output, but Step B needs Step A\'s output. '
        'The agent can never finish.'
    ),
    code(
        'def circular_plan(task, model_fn):\n'
        '    prompt = f"Create a plan for: {task}. Make step 2 depend on step 1, and step 1 depend on step 2."\n'
        '    plan = model_fn([{"role": "user", "content": prompt}])\n'
        '    print("Problematic plan:")\n'
        '    print(plan)\n'
        '    print("\\nFix: Before execution, check for circular deps by building a dependency graph.")\n'
        '\n'
        'circular_plan("Analyze survey data", model)\n'
    ),
    md(
        '### Break 2: Plan Too Fine-Grained\n'
        '\n'
        'Too many tiny steps (20+) cause the agent to lose track of where it is. '
        'The context window fills with partial results.'
    ),
    code(
        'def fine_grained_plan(task, model_fn):\n'
        '    prompt = f"Create a very detailed plan with 15-20 micro-steps for: {task}"\n'
        '    plan = model_fn([{"role": "user", "content": prompt}])\n'
        '    steps = [s for s in plan.split("\\n") if s.strip()]\n'
        '    print(f"Generated {len(steps)} steps.")\n'
        '    print("First 3:", steps[:3] if steps else "none")\n'
        '    print("Last 3:", steps[-3:] if steps else "none")\n'
'    print("\\nFix: Group micro-steps into 3-5 larger phases. "\n'
'          "Keep plans at the right abstraction level.")\n'
        '\n'
        'fine_grained_plan("Research and summarize a topic", model)\n'
    ),
    md(
        '### Break 3: Plan Too Coarse\n'
        '\n'
        'A one-step plan like "solve the problem" defeats the purpose of planning.'
    ),
    code(
        'def coarse_plan(task, model_fn):\n'
        '    prompt = f"Create a plan for: {task}. Make it exactly 1-2 very broad steps."\n'
        '    plan = model_fn([{"role": "user", "content": prompt}])\n'
        '    print("Overly broad plan:")\n'
        '    print(plan)\n'
        '    print("\\nFix: Each step should be a single, executable action. '
        'If a step needs sub-steps, it is too broad.")\n'
        '\n'
        'coarse_plan("Build an AI agent", model)\n'
    ),
    md(
        '## Connection to Agentic AI\n'
        '\n'
        'Planning is what separates reactive systems from truly agentic ones. '
        'A system that only responds to the current input (even with tools) is still reactive. '
        'A system that generates and follows a plan is proactively working toward a goal.\n'
        '\n'
        '**Complexity Ladder mapping:**\n'
        '- **Level 2:** CoT decomposition + simple tool (you did this with linear_planner)\n'
        '- **Level 3:** Plan-then-execute with validation (you did this with validated_plan)\n'
        '- **Level 4:** Multiple cooperating agents with plans (Notebook 05)\n'
    ),
    md(
        '### PBL Reflection\n'
    ),
    code(
        'print("Think about YOUR project:")\n'
        'print("  1. What task does your agent need to decompose into sub-steps?")\n'
        'print("  2. Which planning pattern fits: linear, parallel, or conditional?")\n'
        'print("  3. Where might your plan break? Circular deps? Too many steps?")\n'
        'print("  4. What\'s your validation strategy — how will you know a step succeeded?")\n'
        'print("\\nWrite in your project journal.")\n'
    ),
    md(
        '## Exercises\n'
    ),
    md(
        '### Bronze — Run Planner on Your Domain\n'
        '\n'
        'Change `my_task` to a problem from your own field. '
        'Run the linear planner and observe how it decomposes.'
    ),
    code(
        '# --- Edit this ---\n'
        'my_task = "Analyze patient cognitive load data to detect early burnout indicators"\n'
        '# -----------------\n'
        '\n'
        'plan = linear_planner(my_task, model)\n'
        'print(f"Plan for:\\n  {my_task}\\n")\n'
        'print(plan)\n'
    ),
    md(
        '### Silver — Add Conditional Routing\n'
        '\n'
        'Extend the router_agent to handle more categories. '
        'Add "database" and "image" as new routing options.'
    ),
    code(
        '# --- Extend the router ---\n'
        'def extended_router(query, model_fn):\n'
        '    classification = model_fn([{"role": "user", "content": (\n'
        '        f"Classify this query as: math, weather, search, database, image, or other.\\n"\n'
        '        f"Reply with just the category.\\n"\n'
        '        f"Query: {query}"\n'
        '    )}])\n'
        '    category = classification.strip().lower()\n'
        '    router = {\n'
        '        "math": "→ calculator tool",\n'
        '        "weather": "→ weather API",\n'
        '        "search": "→ web search",\n'
        '        "database": "→ SQL query tool",\n'
        '        "image": "→ image analysis pipeline",\n'
        '    }\n'
        '    return f"ROUTING {router.get(category, f\'→ general LLM ({category})\')}"\n'
        '# --------------------------\n'
        '\n'
        'for q in ["Find user by email", "Analyze this MRI scan", "What is 2+2?"]:\n'
        '    print(f">>> {q}")\n'
        '    print(f"    {extended_router(q, model)}")\n'
    ),
    md(
        '### Gold — Plan with Self-Check Between Steps\n'
        '\n'
        'Build a planning agent that generates a plan, executes each step, '
        'and validates the result before proceeding. If a step fails, the agent '
        're-plans the remaining steps.\n'
        '\n'
        'This integrates planning (Notebook 03) with reflection (Notebook 04 pattern).'
    ),
    code(
        'class AdaptivePlanner:\n'
        '    """Plan, execute, check, and re-plan on failure."""\n'
        '    def __init__(self, model_fn, tools):\n'
        '        self.model = model_fn\n'
        '        self.tools = tools\n'
        '\n'
        '    def run(self, task):\n'
        '        plan = self.model([{"role": "user", "content": (\n'
        '            f"Create a plan for this task. List each step as a separate line.\\n"\n'
        '            f"Task: {task}"\n'
        '        )}])\n'
        '        print("=== PLAN ===")\n'
        '        print(plan, "\\n")\n'
        '\n'
        '        steps = [s.strip() for s in plan.split("\\n") if s.strip() and not s.startswith("#")]\n'
        '        results = []\n'
        '\n'
        '        for i, step in enumerate(steps, 1):\n'
        '            print(f"--- Step {i}: {step[:60]}...")\n'
        '            result = self.model([{\n'
        '                "role": "user",\n'
        '                "content": f"Execute this step: {step}\\nPrevious results: {results}"\n'
        '            }])\n'
        '\n'
        '            check = self.model([{"role": "user", "content": (\n'
        '                f"Did this successfully complete the step? Answer YES or NO.\\n"\n'
        '                f"Step: {step}\\nResult: {result}"\n'
        '            )}])\n'
        '\n'
        '            if "YES" in check:\n'
        '                print(f"  ✓ Step {i} complete")\n'
        '                results.append(f"Step {i} ({step[:30]}...): {result[:100]}")\n'
        '            else:\n'
        '                print(f"  ✗ Step {i} failed. Re-planning from here...")\n'
        '                new_plan = self.model([{"role": "user", "content": (\n'
        '                    f"The step failed: {step}\\n"\n'
        '                    f"Result was: {result}\\n"\n'
        '                    f"Suggest an alternative approach for this step:"\n'
        '                )}])\n'
        '                print(f"  → Alternative: {new_plan[:80]}")\n'
        '                results.append(f"Step {i} (alternative): {new_plan[:100]}")\n'
        '\n'
        '        return results\n'
        '\n'
        'if not use_mock and client is not None:\n'
        '    planner = AdaptivePlanner(model, tools)\n'
        '    planner.run("Research Python ML frameworks and write a summary note")\n'
        'else:\n'
        '    print("Gold exercise — AdaptivePlanner class defined.")\n'
        '    print("Test it with real API mode.")\n'
    ),
    md(
        '## Next Steps\n'
        '\n'
        'You now understand how agents plan: decompose tasks, route between tools, '
        'validate progress, and adapt on failure.\n'
        '\n'
        '**Next notebook:** `04_reflection.ipynb` — "The Agent\'s Critical Eye"\n'
        '\n'
        '> "Planning tells the agent what to do. Reflection tells it if it did well — '
        'and how to improve next time."\n'
    ),
]
notebook = {
    "cells": ALL_CELLS,
    "metadata": {
        "kernelspec": KERNEL_SPEC,
        "language_info": LANG_INFO,
    },
    "nbformat": NB_VERSION,
    "nbformat_minor": NB_MINOR,
}
out_path = os.path.join(os.path.dirname(__file__), "03_planning.ipynb")
with open(out_path, "w") as f:
    json.dump(notebook, f, indent=2)
print(f"Generated: {out_path}")
print(f"Cells: {len(ALL_CELLS)} ({sum(1 for c in ALL_CELLS if c['cell_type']=='markdown')} md, {sum(1 for c in ALL_CELLS if c['cell_type']=='code')} code)")